version: "3"
services:
  react-app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:80"
    depends_on:
      - json-server
    environment:
      - VITE_API_BASE_URL=http://178.128.63.202:3000

  json-server:
    build:
      context: .
      dockerfile: Dockerfile.json-server
    ports:
      - "3000:3000"
    volumes:
      - ./database:/app/database
